# Generated by Django 2.0 on 2018-03-25 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GeoClimate_Capture', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WeatherSnapshot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=500)),
                ('date', models.CharField(max_length=500)),
                ('high_temp', models.CharField(max_length=500)),
                ('low_temp', models.CharField(max_length=500)),
                ('precipitation', models.IntegerField()),
                ('summary', models.CharField(max_length=500)),
            ],
        ),
    ]
