# Generated by Django 2.0 on 2018-03-25 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GeoClimate_Capture', '0002_weathersnapshot'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weathersnapshot',
            name='precipitation',
            field=models.CharField(max_length=500),
        ),
    ]
